# Generated by Django 5.0.4 on 2024-04-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('movie_id', models.IntegerField()),
                ('movie_title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('adult', models.BooleanField()),
                ('rating', models.FloatField()),
                ('overview', models.CharField(max_length=500)),
                ('movie_poster', models.CharField(max_length=100)),
            ],
        ),
    ]
